"""
seed_library.py - one-time import of your NovelFire "Continue Reading" history
into bot.db. Safe to re-run: titles are matched by name, so running it twice
just refreshes progress instead of creating duplicates.

Usage:
    python seed_library.py

Run this once before starting the bot for the first time (or any time you
want to re-sync progress numbers from a fresh export of your history).
"""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from bot.storage import Storage

DB_PATH = os.getenv("DATABASE_PATH", "data/bot.db")

# (title, slug, progress_current, progress_total, last_read_relative)
# Pulled from novelfire.net/account/history pages 1-11.
# progress_current/total are None for entries NovelFire reported as "N/A".
RAW = [
    ("Awakening The Only SSS-Rank Class! Now Even Dragons Obey Me", "awakening-the-only-sss-rank-class-now-even-dragons-obey-me", 822, 822, "14 hours ago"),
    ("Gathering Wives with a System", "gathering-wives-with-a-system", 536, 537, "1 day ago"),
    ("Omega Summoner", "omega-summoner", 2923, 2924, "1 day ago"),
    ("Divine Emperor Demon Emperor", "divine-emperor-demon-emperor", 324, 337, "1 day ago"),
    ("Invincible Beyond Heavens: Cultivating With A Broken EXP System", "invincible-beyond-heavens-cultivating-with-a-broken-exp-system", 447, 450, "1 day ago"),
    ("Eternal Cultivation of Alchemy", "eternal-cultivation-of-alchemy", 3627, 3629, "1 day ago"),
    ("Three Towers Game", "three-towers-game", 10, 1234, "1 week ago"),
    ("New Age Of Summoners", "new-age-of-summoners", 2122, 2122, "2 weeks ago"),
    ("Seven Sins System", "seven-sins-system", 28, 509, "2 weeks ago"),
    ("Super Divine Daoist Skill", "super-divine-daoist-skill", 2, 1010, "3 weeks ago"),
    ("Online Game: Crazy Skeleton", "online-game-crazy-skeleton", 68, 2602, "3 weeks ago"),
    ("Sin System: Demonic Harem After Reincarnation", "sin-system-demonic-harem-after-reincarnation", 254, 257, "4 weeks ago"),
    ("Simplified Beast Evolution Path", "simplified-beast-evolution-path", 5, 439, "4 weeks ago"),
    ("Eternal Emperor's Path to Ascension", "eternal-emperors-path-to-ascension", 336, 367, "4 weeks ago"),
    ("Nine Nether Heavenly Emperor", "nine-nether-heavenly-emperor", 156, 1861, "1 month ago"),
    ("The Lord Of Blood Hill", "the-lord-of-blood-hill", 548, 619, "1 month ago"),
    ("Realm of Myths and Legends", "realm-of-myths-and-legends", 1299, 1300, "1 month ago"),
    ("Online Game: I Started with Max Charisma and Caught the Goddess's Eye", "online-game-i-started-with-max-charisma-and-caught-the-goddesss-eye", 246, 527, "1 month ago"),
    ("Fey Evolution Merchant", "fey-evolution-merchant", 3121, 3121, "1 month ago"),
    ("I will eventually become a divine being through accumulating constantly", "i-will-eventually-become-a-divine-being-through-accumulating-constantly", 54, 670, "1 month ago"),
    ("Child of Destiny", "child-of-destiny", 540, 2206, "1 month ago"),
    ("Harem System In A fantasy World", "harem-system-in-a-fantasy-world", 289, 400, "1 month ago"),
    ("The Ultimate Divine Class", "the-ultimate-divine-class", 8, 698, "1 month ago"),
    ("My Profession is too Personal", "my-profession-is-too-personal", 14, 517, "1 month ago"),
    ("From a Martial Arts Sect to an Immortal Cultivation Sect", "from-a-martial-arts-sect-to-an-immortal-cultivation-sect", 194, 241, "1 month ago"),
    ("God-Tier Extraction Talent: Reincarnated in a Game-like World!", "god-tier-extraction-talent-reincarnated-in-a-game-like-world", 414, 583, "4 months ago"),
    ("Hero of Darkness", "hero-of-darkness", 225, 1243, "4 months ago"),
    ("Path To Godhood Begins With Marrying Wife And Gaining SSS Rank Skill", "path-to-godhood-begins-with-marrying-wife-and-gaining-sss-rank-skill", 78, 581, "4 months ago"),
    ("Beyond SSS-Rank After Getting The God System", "beyond-sss-rank-after-getting-the-god-system", 13, 261, "4 months ago"),
    ("Building The Ultimate Fantasy", "building-the-ultimate-fantasy", 18, 671, "4 months ago"),
    ("The Return of the Legendary All-Master", "the-return-of-the-legendary-all-master", 143, 427, "4 months ago"),
    ("The Incubus System", "the-incubus-system", 830, 877, "4 months ago"),
    ("System's Super Sect", "systems-super-sect", 156, 1178, "5 months ago"),
    ("Global Lord: Start with Divine Favor", "global-lord-start-with-divine-favor", 13, 1090, "5 months ago"),
    ("Starting Off Survival With A Small Treehouse", "starting-off-survival-with-a-small-treehouse", 7, 1185, "5 months ago"),
    ("Incredible Sect Simulator", "incredible-sect-simulator", 6, 1033, "5 months ago"),
    ("With Countless Qualities Bestowed Upon Me, I Shall Ultimately Become Immortal", "with-countless-qualities-bestowed-upon-me-i-shall-ultimately-become-immortal", 4, 1119, "5 months ago"),
    ("SSS-Class Suicide Hunter", "sss-class-suicide-hunter", 8, 404, "5 months ago"),
    ("I got summoned to another world, then married a yandere!", "i-got-summoned-to-another-world-then-married-a-yandere", 6, 391, "5 months ago"),
    ("Eternal Holy Emperor", "eternal-holy-emperor", 379, 1820, "5 months ago"),
    ("Imperial Cultivation", "imperial-cultivation", 571, 1438, "6 months ago"),
    ("One Planet for Everyone! Building Science and Technology Civilization at the Beginning", "one-planet-for-everyone-building-science-and-technology-civilization-at-the-beginning", 90, 565, "6 months ago"),
    ("SSS Awakening: Rebirth of the Strongest Vampire God", "sss-awakening-rebirth-of-the-strongest-vampire-god", 605, 756, "6 months ago"),
    ("Game of the World Tree", "game-of-the-world-tree", 657, 785, "6 months ago"),
    ("The Art of Chaotic Divinity", "the-art-of-chaotic-divinity", 1129, 1478, "7 months ago"),
    ("Ember Dragon", "ember-dragon", 3, 621, "7 months ago"),
    ("From Abyssal Invasion to Bursting Stars with a Single Sword", "from-abyssal-invasion-to-bursting-stars-with-a-single-sword", 1, 1001, "7 months ago"),
    ("Facing an Ancient God for a Year", "facing-an-ancient-god-for-a-year", 1, 2444, "7 months ago"),
    ("Forty Millenniums of Cultivation", "forty-millenniums-of-cultivation", 2, 3523, "7 months ago"),
    ("Level 4 Human in a Ruined World", "level-4-human-in-a-ruined-world", 1, 701, "7 months ago"),
    ("Lord of the Truth", "lord-of-the-truth", 70, 2227, "7 months ago"),
    ("Elf Kingdom: Game of the World Tree", "elf-kingdom-game-of-the-world-tree", 529, 1279, "7 months ago"),
    ("War Sovereign Soaring The Heavens", "war-sovereign-soaring-the-heavens", 2, 4718, "7 months ago"),
    ("Spiritual Energy Rejuvenation: I Began Cultivating By Farming", "spiritual-energy-rejuvenation-i-began-cultivating-by-farming", 6, 2284, "7 months ago"),
    ("I Ascend to the Divine Throne through Arcane Means", "i-ascend-to-the-divine-throne-through-arcane-means", 1360, 1704, "7 months ago"),
    ("I Became The Vampire Progenitor", "i-became-the-vampire-progenitor", 406, 477, "7 months ago"),
    ("Reawakening: Primordial Dragon with Limitless Mana", "reawakening-primordial-dragon-with-limitless-mana", 20, 241, "7 months ago"),
    ("Goblin Simulation: Building a Dark Empire", "goblin-simulation-building-a-dark-empire", 263, 267, "7 months ago"),
    ("Cultivating with Top Enlightenment", "cultivating-with-top-enlightenment", 1, 1077, "7 months ago"),
    ("Witch, Fireball and the Evil God of Steam", "witch-fireball-and-the-evil-god-of-steam", 4, 1095, "8 months ago"),
    ("I Own a Brothel in Another World", "i-own-a-brothel-in-another-world", 1, 285, "8 months ago"),
    ("Atticus's Odyssey: Reincarnated Into A Playground", "atticuss-odyssey-reincarnated-into-a-playground", 1386, 1746, "8 months ago"),
    ("Doomsday: I Obtained A Fallen Angel Pet At The Start Of The Game", "doomsday-i-obtained-a-fallen-angel-pet-at-the-start-of-the-game", 2, 211, "8 months ago"),
    ("Hero or Villain, Both", "hero-or-villain-both", 6, 347, "8 months ago"),
    ("MMORPG: I Can See Hidden Information", "mmorpg-i-can-see-hidden-information", 7, 220, "8 months ago"),
    ("Online: I Can See Health Bars", "online-i-can-see-health-bars", 10, 1442, "8 months ago"),
    ("Lord Evolution: Starting With SS-rank Skills", "lord-evolution-starting-with-ss-rank-skills", 339, 339, "8 months ago"),
    ("Sword Sovereign of the Celestial Emperor", "sword-sovereign-of-the-celestial-emperor", 18, 978, "8 months ago"),
    ("Children of a Lesser God", "children-of-a-lesser-god", 2, 757, "8 months ago"),
    ("Dark Lord Seduction System: Taming Wives, Daughters, Aunts, and CEOs", "dark-lord-seduction-system-taming-wives-daughters-aunts-and-ceos", 7, 1117, "8 months ago"),
    ("First Legendary Dragon: Starting With The Limitless System", "first-legendary-dragon-starting-with-the-limitless-system", 438, 483, "8 months ago"),
    ("Abyss Draconis", "abyss-draconis", 18, 979, "8 months ago"),
    ("Boiling Beast Bloodline", "boiling-beast-bloodline", 1, 2339, "8 months ago"),
    ("Middle-Earth: Kaen, Lord of Light", "middle-earth-kaen-lord-of-light", 1, 287, "8 months ago"),
    ("Arcane Academy: The Divine Extraction Legacy", "arcane-academy-the-divine-extraction-legacy", 1, 1256, "8 months ago"),
    ("SSS-Tier Extraction: From Outcast to Overgod!", "sss-tier-extraction-from-outcast-to-overgod", 34, 326, "8 months ago"),
    ("My Identity Is Becoming More and More Astonishing", "my-identity-is-becoming-more-and-more-astonishing", 8, 406, "8 months ago"),
    ("Star Odyssey", "star-odyssey", 6, 4349, "8 months ago"),
    ("God Ash: Remnants of the fallen.", "god-ash-remnants-of-the-fallen", 1061, 1606, "8 months ago"),
    ("When the plot-skips players into the game world", "when-the-plot-skips-players-into-the-game-world", 13, 1700, "8 months ago"),
    ("First Demonic Dragon", "first-demonic-dragon", 310, 1284, "8 months ago"),
    ("Dragged to Another World… and I Took the Goddess with me!", "dragged-to-another-world-and-i-took-the-goddess-with-me", 14, 196, "8 months ago"),
    ("Death Game: Starting as a Trickster, Pretending to Be a God", "death-game-starting-as-a-trickster-pretending-to-be-a-god", None, None, "8 months ago"),
    ("Landlord World - Start with SSS talent", "landlord-world-start-with-sss-talent", 3, 381, "8 months ago"),
    ("I'm a God in an Online Game", "im-a-god-in-an-online-game", 609, 620, "8 months ago"),
    ("Primordial Chaos Dragon Tower: Harem System", "primordial-chaos-dragon-tower-harem-system", 381, 1666, "8 months ago"),
    ("My Living Shadow System Devours To Make Me Stronger", "my-living-shadow-system-devours-to-make-me-stronger", 3, 1075, "8 months ago"),
    ("MMORPG: War God, You are Invincible Again", "mmorpg-war-god-you-are-invincible-again", 3, 1513, "8 months ago"),
    ("Fake Eunuch: Discovering the Emperor is a Woman!", "fake-eunuch-discovering-the-emperor-is-a-woman", 4, 780, "8 months ago"),
    ("Incubus Living In A World Of Superpower Users", "incubus-living-in-a-world-of-superpower-users", 308, 452, "8 months ago"),
    ("The Villain's Cheat Code: When a Gamer Becomes the Evil God's Sidekick", "the-villains-cheat-code-when-a-gamer-becomes-the-evil-gods-sidekick", 147, 479, "8 months ago"),
    ("Reborn as a Useless Noble with my SSS-Class Innate Talent", "reborn-as-a-useless-noble-with-my-sss-class-innate-talent", 59, 502, "9 months ago"),
    ("Dual Cultivation God Returns", "dual-cultivation-god-returns", 8, 1097, "9 months ago"),
    ("Brand New Life Online: Rise Of The Goddess Of Harvest", "brand-new-life-online-rise-of-the-goddess-of-harvest", 1352, 1941, "9 months ago"),
    ("Dragon Martial Sovereign", "dragon-martial-sovereign", 9, 1091, "9 months ago"),
    ("Da Xuan Martial Saint", "da-xuan-martial-saint", 4, 1532, "9 months ago"),
    ("High-Level Martial Era", "high-level-martial-era", 11, 1963, "9 months ago"),
    ("Pursuit of the Truth", "pursuit-of-the-truth", 2, 1481, "9 months ago"),
    ("Tribulation of Myriad Races", "tribulation-of-myriad-races", 101, 2098, "9 months ago"),
    ("I Become Sect master In Another World", "i-become-sect-master-in-another-world", 1, 212, "9 months ago"),
    ("Trading Cosmic Battleship From The Start", "trading-cosmic-battleship-from-the-start", 42, 554, "9 months ago"),
    ("Global Awakening: Eavesdropping on the SSS-level School Beauty's Inner Voice", "global-awakening-eavesdropping-on-the-sss-level-school-beautys-inner-voice", 204, 945, "9 months ago"),
    ("I Slaughtered Through the Dungeon Worlds with My Cheats", "i-slaughtered-through-the-dungeon-worlds-with-my-cheats", 17, 1677, "9 months ago"),
    ("The Eternal Supreme", "the-eternal-supreme", 1, 2406, "9 months ago"),
    ("Creating Heavenly Laws", "creating-heavenly-laws", 602, 795, "9 months ago"),
    ("Becoming a Deity from Planting the Bodhi Tree", "becoming-a-deity-from-planting-the-bodhi-tree", 1, 1504, "10 months ago"),
    ("Dominion of the Goblin Lord", "dominion-of-the-goblin-lord", 9, 353, "10 months ago"),
    ("World-Ending Demon Emperor", "world-ending-demon-emperor", 7, 2247, "10 months ago"),
    ("My SSS-Rank Dungeon: Reborn In A Reverse World", "my-sss-rank-dungeon-reborn-in-a-reverse-world", 2, 138, "10 months ago"),
    ("The Dark Rebirth of Pandora: Revenge of the Abyss", "the-dark-rebirth-of-pandora-revenge-of-the-abyss", 336, 651, "10 months ago"),
    ("Founder Of The Greatest Noble Family", "founder-of-the-greatest-noble-family", 77, 94, "10 months ago"),
    ("Lackey's Seducing Survival Odyssey", "lackeys-seducing-survival-odyssey", 5, 1667, "10 months ago"),
    ("Floating Islands: SSS Gacha Lord", "floating-islands-sss-gacha-lord", 26, 415, "10 months ago"),
    ("Hero Hack: Reversing Heroes and Raising Harem", "hero-hack-reversing-heroes-and-raising-harem", 5, 377, "10 months ago"),
    ("The King of Beast Trainers", "the-king-of-beast-trainers", 22, 1041, "10 months ago"),
    ("Reincarnated As A Demonic Dragon, I Formed A Pact With A Beautiful Female Lord", "reincarnated-as-a-demonic-dragon-i-formed-a-pact-with-a-beautiful-female-lord", 76, 562, "10 months ago"),
    ("Imp to Demon King: A Journey of Conquest", "imp-to-demon-king-a-journey-of-conquest", 257, 555, "10 months ago"),
    ("Azimuth: The Elden Throne (New Version)", "azimuth-the-elden-throne-new-version", 420, 420, "10 months ago"),
    ("Everyone Is A Lord: My Talent Is A Little Too Strong", "everyone-is-a-lord-my-talent-is-a-little-too-strong", 6, 4605, "10 months ago"),
    ("City of Sin", "city-of-sin", 5, 1439, "10 months ago"),
    ("The Divine Hunter", "the-divine-hunter", 3, 637, "10 months ago"),
    ("Trash of the Count's Family", "trash-of-the-counts-family", 5, 1203, "10 months ago"),
    ("Shattered Innocence: Transmigrated Into a Novel as an Extra", "shattered-innocence-transmigrated-into-a-novel-as-an-extra", 13, 1055, "10 months ago"),
    ("My SSS-Rank Class Is Blood Monarch!", "my-sss-rank-class-is-blood-monarch", 18, 404, "10 months ago"),
    ("SSS-Rank Template! Becoming The Primordial Dragon As A Side Character", "sss-rank-template-becoming-the-primordial-dragon-as-a-side-character", 26, 27, "10 months ago"),
    ("Simulation Towards Immortality In A Group Chat", "simulation-towards-immortality-in-a-group-chat", 12, 1294, "10 months ago"),
    ("Infinite Bloodcore", "infinite-bloodcore", 3, 968, "10 months ago"),
    ("Dark Evolution Begins with Marrying an SSS-CLASS Blind Monster", "dark-evolution-begins-with-marrying-an-sss-class-blind-monster", 16, 155, "11 months ago"),
    ("Global Beast Taming: Awakening Top 10 SSS Talents at the Beginning", "global-beast-taming-awakening-top-10-sss-talents-at-the-beginning", 164, 509, "11 months ago"),
    ("Global Game: I, the Necromancer, am the scourge", "global-game-i-the-necromancer-am-the-scourge", 8, 1289, "11 months ago"),
    ("The Primordial Record", "the-primordial-record", 8, 2240, "11 months ago"),
    ("Weakest Beast Tamer Gets All SSS Dragons", "weakest-beast-tamer-gets-all-sss-dragons", 85, 1048, "11 months ago"),
    ("A Regressor's Tale of Cultivation", "a-regressors-tale-of-cultivation", 2, 863, "11 months ago"),
    ("Return of the Calamity-Class Death Knight", "return-of-the-calamity-class-death-knight", 6, 382, "11 months ago"),
    ("Lord of the Mysteries", "lord-of-the-mysteries", 3, 1432, "11 months ago"),
    ("Life Simulation: I Caused the Female Sword Immortal to Regret Forever", "life-simulation-i-caused-the-female-sword-immortal-to-regret-forever", 183, 482, "11 months ago"),
    ("Throne of Magical Arcana", "throne-of-magical-arcana", 910, 910, "11 months ago"),
    ("Leveling with the Gods", "leveling-with-the-gods", 6, 635, "11 months ago"),
    ("Re-Awakening: I Became a Pay To Win Boss Monster", "re-awakening-i-became-a-pay-to-win-boss-monster", 151, 1018, "11 months ago"),
    ("Having children earns benefit, start competing for dominance in the world by marrying a wife", "having-children-earns-benefit-start-competing-for-dominance-in-the-world-by-marrying-a-wife", 623, 2303, "11 months ago"),
    ("I Enslaved The Goddess Who Summoned Me", "i-enslaved-the-goddess-who-summoned-me", 136, 749, "11 months ago"),
    ("The Noble Lady of Lust", "the-noble-lady-of-lust", 22, 432, "11 months ago"),
    ("Cucking The Demon King", "cucking-the-demon-king", 156, 156, "11 months ago"),
    ("Accidentally invincible!", "accidentally-invincible", 15, 617, "11 months ago"),
    ("Diary of a Dead Wizard", "diary-of-a-dead-wizard", 20, 1037, "11 months ago"),
    ("Naked Sword Art", "naked-sword-art", 345, 533, "1 year ago"),
    ("Clan Immortal Cultivation: I Can See Hints", "clan-immortal-cultivation-i-can-see-hints", 425, 1207, "1 year ago"),
    ("Attacked by the Female Demon at the Beginning", "attacked-by-the-female-demon-at-the-beginning", 2, 347, "1 year ago"),
    ("Kingdom's Bloodline", "kingdoms-bloodline", 4, 622, "1 year ago"),
    ("The Divine Nine-Dragon Cauldron", "the-divine-nine-dragon-cauldron", 693, 3239, "1 year ago"),
    ("Cultivation: When you take things to the extreme", "cultivation-when-you-take-things-to-the-extreme", 4, 1213, "1 year ago"),
    ("Necromancer Of The Shadows", "necromancer-of-the-shadows", 1316, 1391, "1 year ago"),
    ("Primordial Draconic Incubus With A Gourmet Chef System", "primordial-draconic-incubus-with-a-gourmet-chef-system", 168, 245, "1 year ago"),
    ("Douluo: Transforming Xiao Wu into a Zerg Queen Was Just the Beginning", "douluo-transforming-xiao-wu-into-a-zerg-queen-was-just-the-beginning", 81, 179, "1 year ago"),
    ("Reborn As Noble", "reborn-as-noble", 474, 1353, "1 year ago"),
    ("Master of the Demon Emperor", "master-of-the-demon-emperor", 394, 918, "1 year ago"),
    ("Reincarnated Lord: I can upgrade everything!", "reincarnated-lord-i-can-upgrade-everything", 387, 536, "1 year ago"),
    ("Myth Beyond Heaven", "myth-beyond-heaven", 11, 3105, "1 year ago"),
    ("I Can Peek Inside Every Place And Even Record It", "i-can-peek-inside-every-place-and-even-record-it", 135, 290, "1 year ago"),
    ("Dungeon Defense (WN)", "dungeon-defense-wn", 11, 463, "1 year ago"),
    ("Dungeon of Pride, Laplace", "dungeon-of-pride-laplace", 1015, 1015, "1 year ago"),
    ("God Rank Upgrade System", "god-rank-upgrade-system", 7, 1480, "1 year ago"),
    ("I Become Master of Danger Zones as Incubus With Mastery In Genetic", "i-become-master-of-danger-zones-as-incubus-with-mastery-in-genetic", 76, 810, "1 year ago"),
    ("Dimensional Keeper: All My Skills Are at Level 100", "dimensional-keeper-all-my-skills-are-at-level-100", 138, 1720, "1 year ago"),
    ("Apocalypse - Evil Shelter System", "apocalypse-evil-shelter-system", 53, 386, "1 year ago"),
    ("Dark Magus Returns", "dark-magus-returns", 18, 1783, "1 year ago"),
    ("My Blood Legacy: Reincarnated as a Vampire", "my-blood-legacy-reincarnated-as-a-vampire", 165, 526, "1 year ago"),
    ("Building A Business Empire From Scratch In Another World", "building-a-business-empire-from-scratch-in-another-world", 144, 218, "1 year ago"),
    ("My Master Only Breaks Through on the Edge of Death", "my-master-only-breaks-through-on-the-edge-of-death", 142, 1601, "1 year ago"),
    ("Champion Of Lust: Gods Conquer's Harem Paradise!", "champion-of-lust-gods-conquers-harem-paradise", 158, 463, "1 year ago"),
    ("End of Days Game: I'm the Only One Who Can See the Hidden Cues", "end-of-days-game-im-the-only-one-who-can-see-the-hidden-cues", 99, 475, "1 year ago"),
    ("My Celestial Ascension", "my-celestial-ascension", 571, 964, "1 year ago"),
    ("The Last Incubus with The Vice and Valor System", "the-last-incubus-with-the-vice-and-valor-system", 102, 276, "1 year ago"),
    ("Supreme BeastTamer: I Can Copy and Upgrade Skills 10x!", "supreme-beasttamer-i-can-copy-and-upgrade-skills-10x", 84, 831, "1 year ago"),
    ("Floating Island - Triple S Talent", "floating-island-triple-s-talent", 168, 589, "1 year ago"),
    ("Dual Cultivation: Beasts and Women!", "dual-cultivation-beasts-and-women", 10, 249, "1 year ago"),
    ("Beyond the Timescape", "beyond-the-timescape", 1056, 1442, "1 year ago"),
    ("MMORPG: Divine Mech Hunter", "mmorpg-divine-mech-hunter", 441, 2069, "1 year ago"),
    ("Unserious Beast Tamer", "unserious-beast-tamer", 546, 802, "1 year ago"),
    ("LEVEL EVERYTHING UP in my Eldritch Tribe", "level-everything-up-in-my-eldritch-tribe", 25, 401, "1 year ago"),
    ("My Evil System", "my-evil-system", 232, 232, "1 year ago"),
    ("Dual Cultivation", "dual-cultivation", 1107, 1146, "1 year ago"),
    ("I Obtained a Mythic Item", "i-obtained-a-mythic-item", 29, 463, "1 year ago"),
    ("Deities: Starting From Goblins", "deities-starting-from-goblins", 401, 1485, "1 year ago"),
    ("Dungeon Defense", "dungeon-defense", 17, 83, "1 year ago"),
    ("There's Something Wrong With This Account", "theres-something-wrong-with-this-account", 135, 500, "1 year ago"),
    ("King's Awakening", "kings-awakening", 457, 826, "1 year ago"),
    ("Divine Beast Lord: 10000 Amplifier From The Start", "divine-beast-lord-10000-amplifier-from-the-start", 135, 437, "1 year ago"),
    ("Extra's Death: I Am the Son of Hades", "extras-death-i-am-the-son-of-hades", 23, 839, "1 year ago"),
    ("World Evolution! Awakening Limit Grade Talent!", "world-evolution-awakening-limit-grade-talent", 77, 277, "1 year ago"),
    ("Global Job Change: Starting With The Hidden Job, Lord Of The Death", "global-job-change-starting-with-the-hidden-job-lord-of-the-death", 61, 547, "1 year ago"),
    ("Lord of Pets", "lord-of-pets", 3, 1461, "1 year ago"),
    ("Hail the King", "hail-the-king", 345, 1635, "1 year ago"),
    ("Nine Venoms Sect Founder", "nine-venoms-sect-founder", 46, 170, "1 year ago"),
    ("Game of Thrones: I Am The Heir For A Day", "game-of-thrones-i-am-the-heir-for-a-day", 132, 695, "1 year ago"),
    ("Paladin of the Dead God", "paladin-of-the-dead-god", 243, 924, "1 year ago"),
    ("Mythical Era: My Evolution into a Celestial Beast", "mythical-era-my-evolution-into-a-celestial-beast", 4, 1198, "1 year ago"),
    ("Versatile Mage", "versatile-mage", None, None, "1 year ago"),
    ("Grand Ancestral Bloodlines", "grand-ancestral-bloodlines", 61, 2279, "1 year ago"),
    ("Online Game: I Can Use Ultimate Skills Infinitely", "online-game-i-can-use-ultimate-skills-infinitely", 547, 1441, "1 year ago"),
    ("Dragon-Marked War God", "dragon-marked-war-god", 7, 5088, "1 year ago"),
    ("World Defying Dan God", "world-defying-dan-god", 16, 3820, "1 year ago"),
    ("The God of Sky and Earth", "the-god-of-sky-and-earth", 794, 1606, "1 year ago"),
    ("Eternal Sacred King", "eternal-sacred-king", 4, 3380, "1 year ago"),
    ("The King Of Passive Skills", "the-king-of-passive-skills", 76, 596, "1 year ago"),
    ("Online Game: I Began By Enhancing Endlessly With My SSS Rank Talent", "online-game-i-began-by-enhancing-endlessly-with-my-sss-rank-talent", 1, 1014, "1 year ago"),
    ("King of Gods", "king-of-gods", 2, 1585, "1 year ago"),
    ("Age of Gods: Thousand Folds System", "age-of-gods-thousand-folds-system", 47, 203, "1 year ago"),
    ("Online Game: Bugged Talent Unlimited Growth", "online-game-bugged-talent-unlimited-growth", 250, 250, "1 year ago"),
    ("Alchemy Emperor of the Divine Dao", "alchemy-emperor-of-the-divine-dao", 205, 4932, "1 year ago"),
    ("I, The Dragon Overlord", "i-the-dragon-overlord", 656, 669, "1 year ago"),
    ("Divine Throne of Primordial Blood", "divine-throne-of-primordial-blood", 14, 1153, "1 year ago"),
    ("The Lord's Empire", "the-lords-empire", 2, 1728, "1 year ago"),
    ("The Oracle Paths", "the-oracle-paths", 9, 1239, "1 year ago"),
    ("Global Lords: Hundredfold Increments Starting With the Undead", "global-lords-hundredfold-increments-starting-with-the-undead", 239, 1483, "1 year ago"),
    ("Unrivaled Medicine God", "unrivaled-medicine-god", 2, 3122, "1 year ago"),
    ("Global Killing: Awakening SSS-level Talent at the Beginning", "global-killing-awakening-sss-level-talent-at-the-beginning", 6, 1401, "1 year ago"),
    ("Global Evolution: I Have An Attribute Board", "global-evolution-i-have-an-attribute-board", 2, 1124, "1 year ago"),
    ("Global Game: Ten Billion Spirit Energy Coins From The Start", "global-game-ten-billion-spirit-energy-coins-from-the-start", 11, 1823, "1 year ago"),
    ("Global Blessed Land: I Can Add Attributes On The Buildings", "global-blessed-land-i-can-add-attributes-on-the-buildings", 7, 589, "1 year ago"),
    ("I Have Robbed 999 Types Of Powers", "i-have-robbed-999-types-of-powers", 3, 600, "1 year ago"),
    ("The Rise Of The Tamer Family", "the-rise-of-the-tamer-family", 3, 621, "1 year ago"),
    ("I Have A Special Cultivation Talent", "i-have-a-special-cultivation-talent", 1, 1007, "1 year ago"),
    ("Global Demon King: Starting as the Abyssal Dragon", "global-demon-king-starting-as-the-abyssal-dragon", 96, 523, "1 year ago"),
    ("Only I level up", "only-i-level-up", 53, 270, "1 year ago"),
    ("Invincible Divine Dragon's Cultivation System", "invincible-divine-dragons-cultivation-system", 8, 4612, "2 years ago"),
    ("Imperial God Emperor", "imperial-god-emperor", 12, 1370, "2 years ago"),
    ("Nine Yang Sword Saints", "nine-yang-sword-saints", 286, 312, "2 years ago"),
    ("Last Shelter Online", "last-shelter-online", 1, 268, "3 years ago"),
    ("MMORPG : Rise of the Interstellar God", "mmorpg-rise-of-the-interstellar-god", 3, 204, "3 years ago"),
    ("Gods' Impact Online", "gods-impact-online", 418, 463, "3 years ago"),
    ("Lust Knight", "lust-knight", 452, 775, "3 years ago"),
    ("Vampire Lord's Demonic Wives", "vampire-lords-demonic-wives", 1, 141, "3 years ago"),
    ("Becoming the King of A New Filthy World", "becoming-the-king-of-a-new-filthy-world", 15, 403, "3 years ago"),
    ("My Dual-Cultivation System", "my-dual-cultivation-system", 39, 69, "3 years ago"),
    ("I Shall Cuck Everyone", "i-shall-cuck-everyone", 4, 487, "3 years ago"),
]

BASE_URL = "https://novelfire.net/book/"


def main():
    store = Storage(DB_PATH)
    added, updated, completed = 0, 0, 0

    for title, slug, current, total, last_read in RAW:
        status = "completed" if (current and total and current >= total) else "reading"
        if status == "completed":
            completed += 1

        item_id, is_new = store.upsert_seed_item(
            type_="novel",
            title=title,
            url=BASE_URL + slug,
            status=status,
            progress_current=current,
            progress_total=total,
            last_chapter_title=None,
            last_read_at=last_read,
        )
        if is_new:
            added += 1
        else:
            updated += 1

    print(f"Seed complete: {added} new, {updated} updated, {completed} marked completed.")
    print(f"Total titles processed: {len(RAW)}")
    print(f"Database: {os.path.abspath(DB_PATH)}")


if __name__ == "__main__":
    main()
